// Central registry of every game in the hub. Each one carries its own
// gradient + icon, used for its card on the dashboard AND as the hero
// banner on its own page — so the whole app changes color depending
// on which game you're playing.
export const games = [
  {
    id: 'cipher',
    title: 'Code Breaker',
    icon: '🔐',
    tagline: 'Crack a scrambled message before the signal fades away',
    path: '/play/cipher',
    aiPowered: false,
    gradient: 'linear-gradient(135deg, #7C3AED, #06B6D4)',
  },
  {
    id: 'signal-trace',
    title: 'Echo Chain',
    icon: '📡',
    tagline: 'Watch the pattern light up, then play it back from memory',
    path: '/play/signal-trace',
    aiPowered: false,
    gradient: 'linear-gradient(135deg, #EC4899, #F59E0B)',
  },
  {
    id: 'word-ladder',
    title: 'Word Weaver',
    icon: '🪜',
    tagline: 'Change one letter at a time to climb from word to word',
    path: '/play/word-ladder',
    aiPowered: false,
    gradient: 'linear-gradient(135deg, #10B981, #A3E635)',
  },
  {
    id: 'emoji-charades',
    title: 'Emoji Detective',
    icon: '🕵️',
    tagline: 'Piece together a phrase from a handful of emoji clues',
    path: '/play/emoji-charades',
    aiPowered: true,
    gradient: 'linear-gradient(135deg, #FBBF24, #F97316)',
  },
  {
    id: 'reverse-trivia',
    title: 'Quiz Flip',
    icon: '🔄',
    tagline: 'You get the answer first — can you guess the question?',
    path: '/play/reverse-trivia',
    aiPowered: true,
    gradient: 'linear-gradient(135deg, #2563EB, #38BDF8)',
  },
  {
    id: 'mood-match',
    title: 'Vibe Check',
    icon: '🎭',
    tagline: 'Pick the reaction that fits the moment just right',
    path: '/play/mood-match',
    aiPowered: true,
    gradient: 'linear-gradient(135deg, #D946EF, #8B5CF6)',
  },
  {
    id: 'color-deception',
    title: 'Color Trap',
    icon: '🎨',
    tagline: 'Tap the true color of the word, not what it says',
    path: '/play/color-deception',
    aiPowered: false,
    gradient: 'linear-gradient(135deg, #EF4444, #FACC15, #22D3EE)',
  },
  {
    id: 'memory-match',
    title: 'Match Mania',
    icon: '🧠',
    tagline: 'Flip, remember, and hunt down every matching pair',
    path: '/play/memory-match',
    aiPowered: false,
    gradient: 'linear-gradient(135deg, #14B8A6, #3B82F6)',
  },
  {
    id: 'fact-or-fiction',
    title: 'True or Not',
    icon: '🔍',
    tagline: 'One wild claim — is it a real fact or a good fake?',
    path: '/play/fact-or-fiction',
    aiPowered: true,
    gradient: 'linear-gradient(135deg, #DC2626, #F472B6)',
  },
  {
    id: 'riddle-engine',
    title: 'Riddle Me This',
    icon: '🧩',
    tagline: 'Classic riddles, a fresh one every single round',
    path: '/play/riddle-engine',
    aiPowered: true,
    gradient: 'linear-gradient(135deg, #4F46E5, #A855F7)',
  },
  {
    id: 'story-branch',
    title: 'Pick a Path',
    icon: '🌱',
    tagline: 'Choose your move in a tiny scene, see how it plays out',
    path: '/play/story-branch',
    aiPowered: true,
    gradient: 'linear-gradient(135deg, #16A34A, #22D3EE)',
  },
]
